In [1]:
import numpy as np

tensor_1d = np.array([1.3, 2, 4.0, 53, 23.99])

print(tensor_1d)

[  1.3    2.     4.    53.    23.99]


In [2]:
import tensorflow as tf

In [3]:
tf_tensor = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)

In [4]:
with tf.Session() as sess:
    print(sess.run(tf_tensor))
    print(sess.run(tf_tensor[3]))

[  1.3    2.     4.    53.    23.99]
53.0


In [5]:
print(tf_tensor)

Tensor("Const:0", shape=(5,), dtype=float64)


tensor_2d = np.array([(1,2,3), (4, 5, 6), (8, 9, 10, 14), (11, 12, 13)])

print(tensor_2d)

In [38]:
# look at the difference between above diclaration as it will return sequence
# but this will return an array.
# number of elements in each row is equal

tensor_2d = np.array([(1,2,3), (4, 5, 6), (8, 9, 10), (11, 12, 13)])

In [39]:
print(tensor_2d[1][0])

4


In [40]:
print(tensor_2d[0:1][0:1])

[[1 2 3]]


In [42]:
# If tensor_2d were to be the sequence following will return
# (4,) -> this means that it is a sequence and each row does
# not contain equal number of elements
tensor_2d.shape

(4, 3)

In [43]:
x = tf.placeholder("float64", name = 'x')

In [44]:
print(x)

Tensor("x_6:0", dtype=float64)


In [45]:
with tf.Session() as sess:
    print(sess.run(x, feed_dict={x: tensor_2d}))

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  8.   9.  10.]
 [ 11.  12.  13.]]


## The major take away was the difference between sequence and array.

sequence : number of elements in a row can vary


array : number of elements across all the rows are fixed.
        if you are using variable tensor then to run the
        session you need to use :
###    feed_dict={var1: val1, var2: val2, ..} in run method